package pl.edu.pja.s13868.miniproject1.ui.activity;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;


import pl.edu.pja.s13868.miniproject1.EduApplication;
import pl.edu.pja.s13868.miniproject1.R;
import pl.edu.pja.s13868.miniproject1.domain.model.product.Product;
import pl.edu.pja.s13868.miniproject1.domain.persistence.DataHandler;

/**
 * Handles Adding/Editing of a product.
 *
 * @author Krzysztof Dzido <s13868@pjwstka.edu.pl>
 */
public class EditActivity extends AppCompatActivity {
    public final static String TAG_PRODUCT = "TAG_PRODUCT";

    private Product mProduct;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_edit);
        initUI();
    }


    private void initUI() {
        Button save = (Button) findViewById(R.id.save);
        final EditText editText = (EditText) findViewById(R.id.product_edit);

        mProduct = (Product) getIntent().getSerializableExtra(TAG_PRODUCT);

        if (mProduct != null) {
            editText.setText(mProduct.getName());
        }

        save.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mProduct != null) {
                    EduApplication.dataManagerSingleton().product(mProduct.getId(), new DataHandler<Product>() {
                        @Override
                        public void onSuccess(Product pProduct) {
                            pProduct.changeName(editText.getText().toString());

                            EduApplication.dataManagerSingleton().storeProduct(pProduct);
                            Toast.makeText(getApplicationContext(), "Product was persisted", Toast.LENGTH_LONG).show();
                            finish();
                        }
                    });

                } else {
                    if (!editText.getText().toString().isEmpty()) {
                        // ID will be generated by DB
                        final Product product = new Product(editText.getText().toString(), false);

                        EduApplication.dataManagerSingleton().storeProduct(product);
                        finish();

                    } else {
                        Toast.makeText(getApplicationContext(), "Valid product name is required", Toast.LENGTH_LONG).show();
                    }

                }
            }
        });
    }

}
